// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersIDWithBikesParams creates a new GetUsersIDWithBikesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersIDWithBikesParams() *GetUsersIDWithBikesParams {
	return &GetUsersIDWithBikesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersIDWithBikesParamsWithTimeout creates a new GetUsersIDWithBikesParams object
// with the ability to set a timeout on a request.
func NewGetUsersIDWithBikesParamsWithTimeout(timeout time.Duration) *GetUsersIDWithBikesParams {
	return &GetUsersIDWithBikesParams{
		timeout: timeout,
	}
}

// NewGetUsersIDWithBikesParamsWithContext creates a new GetUsersIDWithBikesParams object
// with the ability to set a context for a request.
func NewGetUsersIDWithBikesParamsWithContext(ctx context.Context) *GetUsersIDWithBikesParams {
	return &GetUsersIDWithBikesParams{
		Context: ctx,
	}
}

// NewGetUsersIDWithBikesParamsWithHTTPClient creates a new GetUsersIDWithBikesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersIDWithBikesParamsWithHTTPClient(client *http.Client) *GetUsersIDWithBikesParams {
	return &GetUsersIDWithBikesParams{
		HTTPClient: client,
	}
}

/*
GetUsersIDWithBikesParams contains all the parameters to send to the API endpoint

	for the get users ID with bikes operation.

	Typically these are written to a http.Request.
*/
type GetUsersIDWithBikesParams struct {

	/* ID.

	   ID юзера
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users ID with bikes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersIDWithBikesParams) WithDefaults() *GetUsersIDWithBikesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users ID with bikes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersIDWithBikesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) WithTimeout(timeout time.Duration) *GetUsersIDWithBikesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) WithContext(ctx context.Context) *GetUsersIDWithBikesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) WithHTTPClient(client *http.Client) *GetUsersIDWithBikesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) WithID(id string) *GetUsersIDWithBikesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get users ID with bikes params
func (o *GetUsersIDWithBikesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersIDWithBikesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
