// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_user_microservice_nikita/models"
)

// NewPutUsersIDParams creates a new PutUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutUsersIDParams() *PutUsersIDParams {
	return &PutUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutUsersIDParamsWithTimeout creates a new PutUsersIDParams object
// with the ability to set a timeout on a request.
func NewPutUsersIDParamsWithTimeout(timeout time.Duration) *PutUsersIDParams {
	return &PutUsersIDParams{
		timeout: timeout,
	}
}

// NewPutUsersIDParamsWithContext creates a new PutUsersIDParams object
// with the ability to set a context for a request.
func NewPutUsersIDParamsWithContext(ctx context.Context) *PutUsersIDParams {
	return &PutUsersIDParams{
		Context: ctx,
	}
}

// NewPutUsersIDParamsWithHTTPClient creates a new PutUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutUsersIDParamsWithHTTPClient(client *http.Client) *PutUsersIDParams {
	return &PutUsersIDParams{
		HTTPClient: client,
	}
}

/*
PutUsersIDParams contains all the parameters to send to the API endpoint

	for the put users ID operation.

	Typically these are written to a http.Request.
*/
type PutUsersIDParams struct {

	/* ID.

	   ID юзера
	*/
	ID string

	/* Request.

	   Данные для обновления
	*/
	Request *models.HTTPUpdateUser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutUsersIDParams) WithDefaults() *PutUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put users ID params
func (o *PutUsersIDParams) WithTimeout(timeout time.Duration) *PutUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put users ID params
func (o *PutUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put users ID params
func (o *PutUsersIDParams) WithContext(ctx context.Context) *PutUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put users ID params
func (o *PutUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put users ID params
func (o *PutUsersIDParams) WithHTTPClient(client *http.Client) *PutUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put users ID params
func (o *PutUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put users ID params
func (o *PutUsersIDParams) WithID(id string) *PutUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put users ID params
func (o *PutUsersIDParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the put users ID params
func (o *PutUsersIDParams) WithRequest(request *models.HTTPUpdateUser) *PutUsersIDParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the put users ID params
func (o *PutUsersIDParams) SetRequest(request *models.HTTPUpdateUser) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PutUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
