// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_user_microservice_nikita/models"
)

// PutUsersIDReader is a Reader for the PutUsersID structure.
type PutUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutUsersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutUsersIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutUsersIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /users/{id}] PutUsersID", response, response.Code())
	}
}

// NewPutUsersIDOK creates a PutUsersIDOK with default headers values
func NewPutUsersIDOK() *PutUsersIDOK {
	return &PutUsersIDOK{}
}

/*
PutUsersIDOK describes a response with status code 200, with default header values.

Пользователь обновлен
*/
type PutUsersIDOK struct {
	Payload *models.HTTPUpdateUserResponse
}

// IsSuccess returns true when this put users Id o k response has a 2xx status code
func (o *PutUsersIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put users Id o k response has a 3xx status code
func (o *PutUsersIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put users Id o k response has a 4xx status code
func (o *PutUsersIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put users Id o k response has a 5xx status code
func (o *PutUsersIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put users Id o k response a status code equal to that given
func (o *PutUsersIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put users Id o k response
func (o *PutUsersIDOK) Code() int {
	return 200
}

func (o *PutUsersIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdOK %s", 200, payload)
}

func (o *PutUsersIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdOK %s", 200, payload)
}

func (o *PutUsersIDOK) GetPayload() *models.HTTPUpdateUserResponse {
	return o.Payload
}

func (o *PutUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPUpdateUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutUsersIDBadRequest creates a PutUsersIDBadRequest with default headers values
func NewPutUsersIDBadRequest() *PutUsersIDBadRequest {
	return &PutUsersIDBadRequest{}
}

/*
PutUsersIDBadRequest describes a response with status code 400, with default header values.

Неверный запрос
*/
type PutUsersIDBadRequest struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this put users Id bad request response has a 2xx status code
func (o *PutUsersIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put users Id bad request response has a 3xx status code
func (o *PutUsersIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put users Id bad request response has a 4xx status code
func (o *PutUsersIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put users Id bad request response has a 5xx status code
func (o *PutUsersIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put users Id bad request response a status code equal to that given
func (o *PutUsersIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put users Id bad request response
func (o *PutUsersIDBadRequest) Code() int {
	return 400
}

func (o *PutUsersIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdBadRequest %s", 400, payload)
}

func (o *PutUsersIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdBadRequest %s", 400, payload)
}

func (o *PutUsersIDBadRequest) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *PutUsersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutUsersIDUnauthorized creates a PutUsersIDUnauthorized with default headers values
func NewPutUsersIDUnauthorized() *PutUsersIDUnauthorized {
	return &PutUsersIDUnauthorized{}
}

/*
PutUsersIDUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PutUsersIDUnauthorized struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this put users Id unauthorized response has a 2xx status code
func (o *PutUsersIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put users Id unauthorized response has a 3xx status code
func (o *PutUsersIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put users Id unauthorized response has a 4xx status code
func (o *PutUsersIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put users Id unauthorized response has a 5xx status code
func (o *PutUsersIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put users Id unauthorized response a status code equal to that given
func (o *PutUsersIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put users Id unauthorized response
func (o *PutUsersIDUnauthorized) Code() int {
	return 401
}

func (o *PutUsersIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdUnauthorized %s", 401, payload)
}

func (o *PutUsersIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdUnauthorized %s", 401, payload)
}

func (o *PutUsersIDUnauthorized) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *PutUsersIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutUsersIDForbidden creates a PutUsersIDForbidden with default headers values
func NewPutUsersIDForbidden() *PutUsersIDForbidden {
	return &PutUsersIDForbidden{}
}

/*
PutUsersIDForbidden describes a response with status code 403, with default header values.

Доступ запрещен
*/
type PutUsersIDForbidden struct {
	Payload *models.HTTPErrorResponse
}

// IsSuccess returns true when this put users Id forbidden response has a 2xx status code
func (o *PutUsersIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put users Id forbidden response has a 3xx status code
func (o *PutUsersIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put users Id forbidden response has a 4xx status code
func (o *PutUsersIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this put users Id forbidden response has a 5xx status code
func (o *PutUsersIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this put users Id forbidden response a status code equal to that given
func (o *PutUsersIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the put users Id forbidden response
func (o *PutUsersIDForbidden) Code() int {
	return 403
}

func (o *PutUsersIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdForbidden %s", 403, payload)
}

func (o *PutUsersIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/{id}][%d] putUsersIdForbidden %s", 403, payload)
}

func (o *PutUsersIDForbidden) GetPayload() *models.HTTPErrorResponse {
	return o.Payload
}

func (o *PutUsersIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
