// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sm8ta/webike_user_microservice_nikita/models"
)

// NewPostLoginParams creates a new PostLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostLoginParams() *PostLoginParams {
	return &PostLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostLoginParamsWithTimeout creates a new PostLoginParams object
// with the ability to set a timeout on a request.
func NewPostLoginParamsWithTimeout(timeout time.Duration) *PostLoginParams {
	return &PostLoginParams{
		timeout: timeout,
	}
}

// NewPostLoginParamsWithContext creates a new PostLoginParams object
// with the ability to set a context for a request.
func NewPostLoginParamsWithContext(ctx context.Context) *PostLoginParams {
	return &PostLoginParams{
		Context: ctx,
	}
}

// NewPostLoginParamsWithHTTPClient creates a new PostLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostLoginParamsWithHTTPClient(client *http.Client) *PostLoginParams {
	return &PostLoginParams{
		HTTPClient: client,
	}
}

/*
PostLoginParams contains all the parameters to send to the API endpoint

	for the post login operation.

	Typically these are written to a http.Request.
*/
type PostLoginParams struct {

	/* Request.

	   Данные для входа
	*/
	Request *models.HTTPLoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLoginParams) WithDefaults() *PostLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post login params
func (o *PostLoginParams) WithTimeout(timeout time.Duration) *PostLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post login params
func (o *PostLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post login params
func (o *PostLoginParams) WithContext(ctx context.Context) *PostLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post login params
func (o *PostLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post login params
func (o *PostLoginParams) WithHTTPClient(client *http.Client) *PostLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post login params
func (o *PostLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post login params
func (o *PostLoginParams) WithRequest(request *models.HTTPLoginRequest) *PostLoginParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post login params
func (o *PostLoginParams) SetRequest(request *models.HTTPLoginRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
