// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPUserDTO http user d t o
//
// swagger:model http.UserDTO
type HTTPUserDTO struct {

	// email
	// Example: ivan@example.com
	Email string `json:"email,omitempty"`

	// name
	// Example: Иван Иванов
	Name string `json:"name,omitempty"`

	// user id
	// Example: 12bd787e-05d0-44eb-97e2-8f10e3a564e2
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this http user d t o
func (m *HTTPUserDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this http user d t o based on context it is used
func (m *HTTPUserDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPUserDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPUserDTO) UnmarshalBinary(b []byte) error {
	var res HTTPUserDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
