// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPUpdateUser http update user
//
// swagger:model http.UpdateUser
type HTTPUpdateUser struct {

	// date of birth
	// Example: 1990-01-01
	DateOfBirth string `json:"date_of_birth,omitempty"`

	// email
	// Example: new@example.com
	Email string `json:"email,omitempty"`

	// name
	// Example: Новое имя
	Name string `json:"name,omitempty"`

	// password
	// Example: newpassword123
	Password string `json:"password,omitempty"`
}

// Validate validates this http update user
func (m *HTTPUpdateUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this http update user based on context it is used
func (m *HTTPUpdateUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPUpdateUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPUpdateUser) UnmarshalBinary(b []byte) error {
	var res HTTPUpdateUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
