// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPErrorResponse http error response
//
// swagger:model http.errorResponse
type HTTPErrorResponse struct {

	// message
	// Example: Error
	Message string `json:"message,omitempty"`

	// success
	// Example: false
	Success bool `json:"success,omitempty"`
}

// Validate validates this http error response
func (m *HTTPErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this http error response based on context it is used
func (m *HTTPErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPErrorResponse) UnmarshalBinary(b []byte) error {
	var res HTTPErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
