// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HTTPUserRequest http user request
//
// swagger:model http.UserRequest
type HTTPUserRequest struct {

	// date of birth
	// Example: 1990-01-01
	// Required: true
	DateOfBirth *string `json:"date_of_birth"`

	// email
	// Example: ivan@example.com
	// Required: true
	Email *string `json:"email"`

	// name
	// Example: Иван Иванов
	// Required: true
	Name *string `json:"name"`

	// password
	// Example: password123
	// Required: true
	Password *string `json:"password"`
}

// Validate validates this http user request
func (m *HTTPUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateOfBirth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPUserRequest) validateDateOfBirth(formats strfmt.Registry) error {

	if err := validate.Required("date_of_birth", "body", m.DateOfBirth); err != nil {
		return err
	}

	return nil
}

func (m *HTTPUserRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *HTTPUserRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *HTTPUserRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this http user request based on context it is used
func (m *HTTPUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPUserRequest) UnmarshalBinary(b []byte) error {
	var res HTTPUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
